# Permalinks
permalink:           pretty

# Setup
title:               P. Nieto Ramos
tagline:             Exploring Data Science
url:                 http://pnietoramos.github.io/
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Pablo Nieto Ramos
  email:             pnietoramos@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/pnietoramos

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
